# Generated by Django 5.0.4 on 2024-05-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_whishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Whishlist',
            new_name='Wishlist',
        ),
    ]
